# Configuration for jekyll
# NOTICE: GitHub forces to set `safe: true` in order to prohibit using plugins.
safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vender']

url: http://2nd-ndn-hackathon.named-data.net
baseurl: 

deadlines:
- name: Submission deadline
  date:
  - <del>March 6, 2016</del>
  - March 10, 2016
- name: Acceptance notification
  date: March 13, 2016

# Configuration for permalink
permalink: /:page.html

# Configuration for site
title: 2nd Named Data Networking (NDN) Hackathon
short_title: 2nd NDN Hackathon
description: March 20-21, 2016, UC San Diego Campus, La Jolla, CA
author: 2nd NDN Hackathon Organizing Committee
email: 2nd-ndn-hackathon@named-data.net

# Configuration for blog
lang: en
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Call for Hack Proposals
  link: /cfh.html
- name: Committees
  link: /committees.html
- name: Program
  link: /program.html
- name: Participant Guide
  link: /guide.html

# Configuration for responsive break point when using 'custom'.
responsive_bp: 768

# Configuration for asides.html
# CAUTION: `themes` should be false to put the script.html at the bottom.
asides:
    github: true
    tweets: false
    archive_tabs: false

# Configuration for jQuery
jquery_ver: 1.10.2

#feedburner:
#    id: YOUR_SITE_ID

#google_analytics:
#    account: UA-XXXXX-X

google_plus_one:
    size: medium

# `xfbml` will break some styles on android 2.3 native browser (Optimus L-01D).
# `locale`: ja_JP, en_US, es_LA, fr_FR, de_DE, it_IT, zh_CN, ko_KR, ...
# facebook:
#     xfbml: false
#     locale: en_US

twitter:
    username: NamedData
    count: 5
    exclude_replies: true
    show_screen_name: true
    show_follower_count: false
    widget_id: 698294519054278656

github:
   username: 2nd-ndn-hackathon
   count: 5

# pocket: true

# hatena: true
